config/routes.rb
Rails.application.routes.draw do
  root to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'

  resources :users, only: %i(index show create edit update destroy)

  namespace :admin do
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'

    resources :users, only: %i(index destroy)
    resources :questions, only: %i(index destroy)
  end

  resources :questions do
    resources :answers, only: %i(create)
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #letter_opener_web
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :content, presence: true, length: {maximum: 1000}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true, length: { maximum: 30}
  validates :content, presence: true
  validate :validate_name_not_including_comma

  belongs_to :user
  has_many :answers, dependent: :destroy

  scope :recent, -> {order(created_at: :desc)}

  #ransack
  def self.ransackable_attributes(auth_object = nil)
    %w[title]
  end
  def self.ransackable_associations(auth_object = nil)
    []
  end

  private
    def validate_name_not_including_comma
      errors.add(:title, 'にカンマを含めることはできません') if title&.include?(',')
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :avatar

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
  uniqueness: { case_sensitive: false }

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  before_action :admin_user

  def index
    @q = Question.ransack(params[:q])
    @questions = @q.result(distinct: true).page(params[:page])
  end

  private
    def admin_user
      redirect_to root_path, warning: '権限がありません' unless current_user.admin?
    end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password]) && user.admin?
      session[:user_id] = user.id
      redirect_to admin_users_path, flash: {success: "ログインしました。" }
    else
      flash.now[:destroy] = "ログインに失敗しました。"
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url, flash: {danger: 'ログアウトしました。'}
  end

  private
    def session_params
      params.require(:admin_session).permit(:email, :password)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page])
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_users_url, flash: {success: "ユーザ「#{user.name}」を削除しました。"}
  end

  private
    def admin_user
      redirect_to root_path, warning: '権限がありません' unless current_user.admin?
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(user_id: current_user.id, content: params[:answer][:content])
    @user = User.where(id: @question.user).where(id: @answer.user).where.not(id: current_user.id).distinct
    binding.pry
    if @answer.save
      @user.each do |user|
        AnswerMailer.with(question: @question, answer: @answer, user: user).answer_email.deliver_now
      end
      redirect_to question_path(@question), flash: {success: '回答をしました。'}
    else
      flash.now[:danger] = "回答に失敗しました。"
      render "questions/show"
    end
  end

  private
    def answer_params
      params.require(:answer).permit(:content)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_url unless current_user
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i(show edit update destroy)

  def index
    @q = Question.ransack(params[:q])
    # @questions = @q.result(distinct: true).page(params[:page])
    
    if params[:is_solved] == 'false'
      @questions = Question.where(is_solved: false).page(params[:page])
    elsif params[:is_solved] == 'true'
      @questions = Question.where(is_solved: true).page(params[:page])
    else
      @questions = Question.page(params[:page])
    end
  end

  def show
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      User.where.not(id: current_user.id).each do |user|
        QuestionMailer.with(user: user, question: @question, question_user: @question.user.name).creation_email.deliver_now
      end
      redirect_to question_path(@question), flash: {success: "タスク「#{@question.title}」を登録しました。"} 
    else
      flash[:alert] = '登録に失敗しました。'
      render :new
    end
  end

  def edit
  end

  def update
    @question.update!(question_params)
    redirect_to questions_url, flash: {success: "質問「#{@question.title}」を更新しました"}
  end

  def destroy
    @question.destroy
    redirect_to questions_url, flash: {warning: "質問「#{@question.title}」を削除しました。"}
  end


  private

    def question_params
      params.require(:question).permit(:title, :content, :is_solved)
    end

    def set_question
      @question = Question.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to questions_path, flash: {success: 'ログインしました。'}
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to login_path, flash: {success: 'ログアウトしました。'}
  end

  private

    def session_params
      params.require(:session).permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i(new create)
  before_action :set_user, only: %i(show edit update destroy)

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, flash: {success: "ユーザ「#{@user.name}」を登録しました。"}
    else
      flash.now[:danger] = "ユーザー登録に失敗しました。"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
      if @user.update(user_params)
        redirect_to user_path(@user), flash: {success: "ユーザー情報を更新しました。"}
      else
        flash[:danger] = "ユーザーの更新に失敗しました。"
        render :edit
      end
  end

  def destroy
    @user.destroy
    redirect_to signup_url, flash: {warning: "ユーザ「#{@user.name}」を削除しました。"}
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :avatar, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/questions/index.html.erb
<div class="py-4">
  管理者画面:質問一覧
</div>

<%= search_form_for @q, class: 'mb-5' do |f| %>
  <div class="row">
    <div class="form-group col-8">
      <%= f.search_field :title_cont, class: 'form-control', placeholder: '検索ワード' %>
    </div>
    <div class="form-group col-4">
      <%= f.submit '検索', class: 'btn btn-info'%>
    </div>
  </div>
<% end %>

<% @questions.each do |question| %>
  <div class="pb-3">
    <span style="padding:0 10px 0 0;">
      <% if question.user.avatar.attached?%>
        <%= image_tag question.user.avatar, class: 'header-avatar img-fluid'  %>
      <% else %>
        <%= link_to image_tag('avatar.png', class: 'header-avatar img-fluid'), user_path(question.user) %>
      <% end %>
    </span>
    <span style="font-size:25px; padding:0 20px 0 0;">
      <%= question.title %>
    </span>
    <span>
      <%= link_to '削除', question, method: :delete, class: 'btn btn-danger', data: {confirm: "ユーザー「#{question.title}」を削除します。よろしいですか？"}%>
    </span>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<p>Find me in app/views/admin/users/edit.html.erb</p>

app/views/admin/users/index.html.erb
<div class="py-4">
  管理者画面:ユーザ一覧
</div>

<%= search_form_for @q, class: 'mb-5' do |f| %>
  <div class="row">
    <div class="form-group col-8">
      <%= f.search_field :name_cont, class: 'form-control', placeholder: '検索ワード' %>
    </div>
    <div class="form-group col-4">
      <%= f.submit '検索', class: 'btn btn-info'%>
    </div>
  </div>
<% end %>

<% @users.each do |user| %>
  <div class="pb-3">
    <span style="padding:0 10px 0 0;">
      <% if user.avatar.attached?%>
        <%= image_tag user.avatar, class: 'header-avatar img-fluid'  %>
      <% else %>
        <%= link_to image_tag('avatar.png', class: 'header-avatar img-fluid'), user_path(user) %>
      <% end %>
    </span>
    <span style="font-size:25px; padding:0 20px 0 0;">
      <%= user.name %>
    </span>
    <span>
      <%= link_to '削除', user, method: :delete, class: 'btn btn-danger', data: {confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？"}%>
    </span>
  </div>
<% end %>

app/views/admin/users/new.html.erb
<h1>Admin::Users#new</h1>
<p>Find me in app/views/admin/users/new.html.erb</p>

app/views/admin/users/show.html.erb
<h1>Admin::Users#show</h1>
<p>Find me in app/views/admin/users/show.html.erb</p>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-expand-lg navbar-light ">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <%= image_tag 'logo-sm.png' %>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end " id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <% if current_user %>
            <li class="nav-item">
              <%= link_to 'ログアウト', logout_path, method: :delete ,class: 'nav-link' %>
            </li>
          <% end %>
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to 'ユーザー一覧', admin_users_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to '質問一覧', admin_questions_path, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'ユーザー一覧', users_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to '質問一覧', questions_path, class: 'nav-link' %>
            </li>
          <%end%>
          <li class="nav-item">
            <% if current_user.avatar.attached?%>
              <%= image_tag current_user.avatar, class: 'header-avatar img-fluid'  %>
            <% else %>
              <%= link_to image_tag('avatar.png', class: 'header-avatar img-fluid'), user_path(current_user) %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
      <%= render partial: 'layouts/header'%>
    <% end %>
    <div class="container">
      <%# flash %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
        <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<% if question.errors.present? %>
  <ul id="error_explation">
    <% question.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="mt-5 text-center">
  <%= form_with model: question, local:true do |f| %>
    <div class="form-group pb-4">
      <%= f.text_field :title, class: 'form-control text-center', placeholder: '質問タイトル', id: 'question_title' %>
    </div>
    <div class="form-group pb-4">
      <%= f.text_area :content, class: 'form-control text-center', placeholder: '質問内容', id: 'question_content'%>
    </div>
    <%= f.submit "#{btn_name}", class: 'btn btn-info btn-lg' %>
  <% end %>
</div>

app/views/questions/edit.html.erb
<%= render partial: 'form', locals: { question: @question, btn_name: '更新'} %>

app/views/questions/index.html.erb
<div class="mb-4">
  <%= link_to '全て', questions_path, class: "#{ params[:is_solved].nil? ? 'btn btn-info text-white' : 'btn btn-outline-info text-black' }" %>
  <%= link_to '解決済み', questions_path(is_solved: true) , class: "#{ params[:is_solved] == "true" ? 'btn btn-info text-white' : 'btn btn-outline-info text-black' }" %>
  <%= link_to '未解決', questions_path(is_solved: false), class: "#{ params[:is_solved] == "false" ? 'btn btn-info text-white' : 'btn btn-outline-info text-black' }" %>
</div>

<%= search_form_for @q, class: 'mb-5' do |f| %>
  <div class="row">
    <div class="col-9">
      <%= f.search_field :title_cont, class: 'form-control', placeholder: '検索ワード' %>
    </div>
    <ul class="col-3">
      <%= f.submit '検索', class: 'btn btn-info'%>
    </div>
  </div>
<% end %>

<div class="container">
  <ul class="questions-list">
    <% @questions.each do |question| %>
    <li>
      <% if question.user.avatar.attached? %>
        <%= image_tag question.user.avatar, class: 'users-img' %>
      <% else %>
        <%= link_to image_tag('avatar.png', class: 'header-avatar img-fluid'), user_path(question.user) %>
      <% end %>
      <span>
        <%= link_to question.title, question %>
      </span>
      <span>
      <%if question.is_solved? %>
        <span class="bg-secondary">解決済み</span>
      <% else %>
        <span class="bg-success text-white">未解決</span>
      <% end %>
      </span>
    </li>
    <% end %>
  </ul>
</div>

<div class="mb-3">
  <%= paginate @questions %>
</div>

app/views/questions/new.html.erb
<%= render partial: 'form', locals: { question: @question, btn_name: '登録'} %>

app/views/questions/show.html.erb
<div>
  <ul>
    <li class="pb-5">
      <span style="padding:0 20px 0 0;" class="user-avatars">
      <% if current_user.avatar.attached? %>
        <%= image_tag current_user.avatar %>
      <% else %>
        <%= link_to image_tag('avatar.png', class: 'header-avatar img-fluid'), user_path(current_user) %>
      <% end %>
      </span>
      <span style="font-size: 25px;">
      <%= @question.title%>
      </span>
      <% if current_user.id == @question.user_id %>
        <span class="" style="padding:0 15px 0 50px;">
          <%= link_to '編集', edit_question_path(@question), class: 'btn btn-info text-white' %>
        </span>
        <span class="mr-4" style="padding:0 15px 0 0;" >
          <%= link_to '削除', @question, method: :delete, data: { confirm: "質問「#{@question.title}」を削除してもよろしいですか？"} , class: 'btn btn-danger' %>
        </span>
        <span >
        <% if @question.is_solved? %>
          <%= link_to '解決済み', question_path(@question.id, params: {question: {is_solved: false}}), method: :put, class: "btn btn-secondary" %>
        <% else %>
          <%= link_to '未解決', question_path(@question.id, params: {question: {is_solved: true}}), method: :put , class: "btn btn-success"%>
        <% end %>
        </span>
      <% end %>
    </li>
    <li class="border-bottom">
      <%= @question.content %>
    </li>
  </ul>
</div>

<div class="text-center">
  <%= form_with model: [@question, @answer], local: true do |f| %>
    <div class="form-group">
      <%= f.text_area :content, class: 'form-control' %>
    </div>
    <div class="pt-4">
      <%= f.submit '回答する', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>
<div class="pt-5">
  <% @question.answers.each do |answer| %>
    <p class="border-bottom pb-3">
      <span style="padding:0 20px 0 0;" >
        <% if answer.user.avatar.attached?%>
          <%= image_tag answer.user.avatar, class: "users-img"  %>
        <% else %>
          <%= link_to image_tag('avatar.png', class: 'header-avatar img-fluid'), user_path(current_user) %>
        <% end %>
      </span>
      <%= answer.content %>
    </p>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>ユーザ編集</h1>

<%= form_with model: @user, local: true do |f| %>
    <div class="form-group">
      <%= f.file_field :avatar, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.text_field :name, class: 'form-control', placeholder: 'お名前'%>
    </div>
    <div class="form-group">
      <%= f.text_field :email, class: 'form-control', placeholder: 'メールアドレス' %>
    </div>
    <div class="form-group">
      <%= f.text_field :password, class: 'form-control', placeholder: 'パスワード' %>
    </div>
    <div class="form-group">
      <%= f.text_field :password_confirmation, class: 'form-control', placeholder: 'パスワード確認' %>
    </div>
    <%= f.submit '登録', class: 'btn btn-info' %>
<% end %>

app/views/users/index.html.erb
<div class="mt-4">
  <% @users.each do |user| %>
    <div class="border-bottom mb-3 pb-2">
      <span style="padding: 0 20px 0 0 ;">
        <% if user.avatar.attached? %>
          <%=link_to image_tag(user.avatar, class: 'users-img'), user_path(user) %>
        <% else %>
          <%= link_to image_tag('avatar.png', class: 'header-avatar img-fluid'), user_path(user) %>
        <% end %>
      </span>
      <span>
        <%= user.name %>
      </span>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
  <h1 class="text-center my-5">
    <%= image_tag 'logo.png'%>
  </h1>
  <%= form_with model: @user, local: true do |f| %>
    <div class="form-group pb-4">
      <%= f.file_field :avatar, class: 'form-control text-center'%>
    </div>
    <div class="form-group pb-4">
      <%= f.text_field :name, class: 'form-control text-center', placeholder: 'お名前'%>
    </div>
    <div class="form-group pb-4">
      <%= f.text_field :email, class: 'form-control text-center', placeholder: 'メールアドレス' %>
    </div>
    <div class="form-group pb-4">
      <%= f.text_field :password, class: 'form-control text-center', placeholder: 'パスワード' %>
    </div>
    <div class="form-group pb-4">
      <%= f.text_field :password_confirmation, class: 'form-control text-center', placeholder: 'パスワード確認' %>
    </div>
    <div class="text-center">
      <%= f.submit '登録', class: 'btn btn-info btn-lg' %>
    </div>
  <% end %>

app/views/users/show.html.erb
<h1>ユーザー詳細</h1>

<div class="row pt-5">
  <div class="col-4 user-avatars">
    <% if @user.avatar.attached? %>
      <%= image_tag @user.avatar, class: "img-fluid "%>
    <% else %>
      <%= image_tag 'avatar.png', class: "img-fluid rounded" %>
    <% end %>
  </div>
  <div class="col-8">
    <ul class="user-profile">
      <li class="user-name" style="font-size: 30px;">
        <%= @user.name %>
      </li>
      <li class="user-email" style="font-size: 30px;">
        <%= @user.email %>
      </li>
    </ul>
  </div>
</div>
<% if current_user.id == @user.id %>
  <div class="row pt-4">
    <span class="col-3" style="padding:0 15px 0 50px;">
      <%= link_to '編集', edit_user_path(@user), class: 'btn btn-info text-white' %>
    </span>
    <span class="col-3" style="padding:0 15px 0 0;" >
      <%= link_to '削除', @user, method: :delete, data: { confirm: "質問「#{@user.name}」を削除してもよろしいですか？"} , class: 'btn btn-danger' %>
    </span>
  </div>
<% end %>